name: Reminder Cron

# Run at minute 0 of every hour
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  # also allow manual trigger

jobs:
  call-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Reminder Function
        run: |
          echo "Calling /api/reminders at $(date -u)"
          curl -s https://pilo-dent-frontend.vercel.app/api/reminders

