name: Reminder Cron

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  call-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Reminder Function
        run: |
          echo "Calling reminders at $(date -u)"
          curl -s https://pilo-dent-frontend.vercel.app/api/reminders

